# generated by datamodel-codegen:
#   filename:  single_chunk.json
#   timestamp: 2026-05-25T05:08:46+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Parent(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Child(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Bbox(BaseModel):
    l: float
    t: float
    r: float
    b: float
    coord_origin: str


class ProvItem(BaseModel):
    page_no: int
    bbox: Bbox
    charspan: list[int]


class DocItem(BaseModel):
    self_ref: str
    parent: Parent
    children: list[Child]
    content_layer: str
    label: str #https://github.com/docling-project/docling-core/blob/main/docling_core/types/doc/labels.py
    prov: list[ProvItem]
    meta: dict[str, Any] | None = None


class Origin(BaseModel):
    mimetype: str
    binary_hash: int
    filename: str


class Meta(BaseModel):
    schema_name: str
    version: str
    doc_items: list[DocItem]
    headings: list[str]
    origin: Origin


class SingleChunkModel(BaseModel):
    text: str
    meta: Meta
